modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Sweenus/SimplySwords/issues"
license = "Timefall Development License"

[[mixins]]
config = "simplyswords.mixins.json"
[[mixins]]
config = "simplyswords-common.mixins.json"

[[mods]]
modId = "simplyswords"
version = "${version}"
displayName = "Simply Swords"
authors = "Sweenus"
credits="Konsyliarz42 (Art), KreloX (Contributor), Fzzyhmstrs (Contributor), RosemaryThyme (Contributor), DestrSpirit (Contributor)"
description = '''
A variety of unique weapons to add to your minecraft repertoire
'''
logoFile = "SimplySwordsLogoFinal2.gif"

[[dependencies.simplyswords]]
modId = "neoforge"
mandatory = true
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyswords]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21, 1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyswords]]
modId = "architectury"
mandatory = true
versionRange = "[5.12.42,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simplyswords]]
modId = "fzzy_config"
mandatory = true
versionRange = "[0.5.6,)"
ordering = "AFTER"
side = "BOTH"