org.gradle.jvmargs=-Xmx4048M

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

archives_base_name=simplyswords
archives_name=simplyswords
mod_version=1.63.0-1.21.1
maven_group=net.sweenus

architectury_api_version=13.0.8

fabric_loader_version=0.16.10
fabric_api_version=0.115.0+1.21.1

forge_version=1.21.1-52.0.53
neoforge_version = 21.1.125
yarn_mappings=1.21.1+build.3
yarn_mappings_patch_neoforge_version = 1.21+build.4

mixin_extras_version=0.5.0-beta.3
spellpower_version=1.0.2+1.21.1
lambdynlights_version=4597897
spruceui_version=5.0.0+1.20
fzz_config_version=0.6.6+1.21
mod_menu_version=11.0.2
eldritch_end_version=5035580
necronomicon_version=5041803
oracle_index_version=7590937
openpac_version=6242911
mythicmetals_version=0.24.0+1.21
irons_spells_version=1.21-3.8.0
rei_version=16.0.799
emi_version=1.1.22+1.21.1