blank_issues_enabled: false
contact_links:
  - name: Community Discord
    url: https://discord.gg/tRUdaHx7gG
    about: For questions and general support, please join the Discord. The Github issue tracker is only for bug reports.
