package net.sweenus.simplyswords.api.ability;

import java.util.EnumMap;
import java.util.Map;

public final class Phase5AbilityTuning {
    public enum Setting {
        COOLDOWN_TICKS(0, 72000), DURATION_TICKS(0, 72000), COLLAPSE_DURATION_TICKS(0, 72000),
        INTERVAL_TICKS(1, 72000), LOCKOUT_TICKS(0, 72000), REFUND_TICKS(0, 72000),
        CHANCE(0, 100), DAMAGE_MULTIPLIER(0, 10), PERIODIC_DAMAGE_MULTIPLIER(0, 10),
        FINAL_DAMAGE_MULTIPLIER(0, 10), SECONDARY_DAMAGE_MULTIPLIER(0, 10),
        HEAL_MULTIPLIER(0, 10), DAMAGE_REDUCTION(0, 1), INCOMING_MULTIPLIER(0, 10),
        OUTGOING_MULTIPLIER(0, 10), PER_STACK_MULTIPLIER(0, 10), GENERATION_MULTIPLIER(0, 10),
        RADIUS(0, 64), RANGE(0, 128), RETARGET_RANGE(0, 128), MIN_LENGTH(0, 64),
        PULL_STRENGTH(0, 16), RADIUS_GROWTH(0, 16), RUPTURE_LENGTH(0, 128),
        RUPTURE_WIDTH(0, 64), RUPTURE_KNOCK_UP(0, 16), SPEED(0, 16),
        TARGET_CAP(0, 64), SEARCH_CAP(0, 64), COUNT(0, 64), STACK_CAP(0, 64),
        SPREAD_CAP(0, 64), GENERATION_CAP(0, 64), PULSE_COUNT(0, 64), WISP_COUNT(0, 64),
        HEAT_GAIN(0, 100), HEAT_MAX(1, 100), HEAT_FLOOR(0, 100), VENT_DRAIN(1, 100),
        MAX_PRESSURE(1, 10000), TURN_DEGREES(0, 180),
        FIRE_TICKS(0, 72000), STATUS_DURATION_TICKS(0, 72000), STATUS_AMPLIFIER(0, 10),
        ABSORPTION(0, 40),

        HEARTH_CHAIN_DURATION_TICKS(0, 72000), HEARTH_BRAND_DURATION_TICKS(0, 72000),
        HEARTH_BIND_RANGE(0, 128), HEARTH_MIN_LENGTH(0, 64), HEARTH_BREAK_RANGE(0, 128),
        HEARTH_ECHO_DAMAGE_MULTIPLIER(0, 10), HEARTH_SNAP_DAMAGE_MULTIPLIER(0, 10),
        HEARTH_FINAL_DAMAGE_MULTIPLIER(0, 10), HEARTH_SNAP_RADIUS(0, 64),
        HEARTH_ECHO_FIRE_TICKS(0, 72000), HEARTH_BRAND_HIT_FIRE_TICKS(0, 72000),
        HEARTH_SNAP_PRESSURE_MULTIPLIER(0, 10), HEARTH_FINAL_KNOCKBACK_MULTIPLIER(0, 16),
        HEARTH_CAST_ABSORPTION(0, 40), HEARTH_CAST_ABSORPTION_DURATION_TICKS(0, 72000),
        HEARTH_FIRE_DAMAGE_REDUCTION(0, 1), HEARTH_SNAP_RESISTANCE_DURATION_TICKS(0, 72000),
        HEARTH_SNAP_RESISTANCE_MAX_TICKS(0, 72000), HEARTH_BOUND_DAMAGE_REDUCTION(0, 1),
        HEARTH_BOUND_DAMAGE_REDUCTION_RANGE(0, 128), HEARTH_BRAND_ABSORPTION(0, 40),
        HEARTH_BRAND_ABSORPTION_LOCKOUT_TICKS(0, 72000), HEARTH_CHAIN_PRESERVE_TICKS(0, 72000),
        HEARTH_COMPLETION_ABSORPTION(0, 40), HEARTH_COMPLETION_ABSORPTION_DURATION_TICKS(0, 72000),
        HEARTH_COMPLETION_MIN_CHAINS(0, 64), HEARTH_ANCHOR_SPEED_MULTIPLIER(0, 1),
        HEARTH_BRAND_HIT_DAMAGE_MULTIPLIER(0, 10), HEARTH_REACTIVE_BRAND_DURATION_TICKS(0, 72000),
        HEARTH_REACTIVE_BRAND_LOCKOUT_TICKS(0, 72000), HEARTH_BRAND_SPREAD_COUNT(0, 64),
        HEARTH_BRAND_SPREAD_RANGE(0, 128), HEARTH_BRAND_SPREAD_DURATION_TICKS(0, 72000),
        HEARTH_FORCED_SNAP_TICKS(0, 72000), HEARTH_REBIND_COUNT(0, 64),
        HEARTH_REBIND_RANGE(0, 128), HEARTH_REBIND_DAMAGE_MULTIPLIER(0, 10),
        EMBERBLADE_FLAME_BANK_DURATION_TICKS(0, 72000), EMBERBLADE_FULL_CHARGE_MULTIPLIER(0, 10),
        EMBERLASH_ECHO_DAMAGE_MULTIPLIER(0, 10),
        FLAMEWIND_HASTE_DURATION_TICKS(0, 72000), FLAMEWIND_HASTE_AMPLIFIER(0, 10),
        FLAMEWIND_DRAFT_RANGE(0, 128), FLAMEWIND_DRAFT_PER_SEED(0, 10), FLAMEWIND_DRAFT_CAP(0, 10),
        FLAMEWIND_SEED_RANGE(0, 128), FLAMEWIND_RETARGET_RANGE(0, 128),
        FLAMEWIND_SPREAD_RANGE(0, 128), FLAMEWIND_SEARCH_CAP(0, 64),
        FLAMEWIND_SPREAD_DURATION_FRACTION(0, 10), FLAMEWIND_GENERATION_CAP(0, 64),
        FLAMEWIND_GENERATION_MULTIPLIER(0, 10), FLAMEWIND_HARVEST_REFUND_TICKS(0, 72000),
        FLAMEWIND_HARVEST_REFUND_CAP_TICKS(0, 72000), FLAMEWIND_CHAIN_WINDOW_TICKS(0, 72000),
        FLAMEWIND_CHAIN_DAMAGE_MULTIPLIER(0, 10), FLAMEWIND_FLASH_COUNT(1, 64),
        FLAMEWIND_FLASH_WINDOW_TICKS(0, 72000), FLAMEWIND_FLASH_HASTE_TICKS(0, 72000),
        FLAMEWIND_FLASH_HASTE_AMPLIFIER(0, 10), FLAMEWIND_RECAST_LOCKOUT_TICKS(0, 72000),
        FLAMEWIND_RESERVE_ABSORPTION(0, 40), FLAMEWIND_RESERVE_ABSORPTION_CAP(0, 40),
        FLAMEWIND_RESERVE_ABSORPTION_TICKS(0, 72000), FLAMEWIND_RESET_KILL_COUNT(1, 64),
        FLAMEWIND_RESET_REFUND_FRACTION(0, 1), FLAMEWIND_KNOCKBACK_MULTIPLIER(0, 10),
        FLAMEWIND_DEATH_DAMAGE_MULTIPLIER(0, 10),

        MOLTEN_MELEE_HEAT_GAIN(0, 100), MOLTEN_INCOMING_HEAT_GAIN(0, 100),
        MOLTEN_INCOMING_PENALTY_MULTIPLIER(0, 10), MOLTEN_REDLINE_THRESHOLD(0, 100),
        MOLTEN_REDLINE_DAMAGE_MULTIPLIER(0, 10), MOLTEN_HEAT_SINK_ABSORPTION(0, 40),
        MOLTEN_HEAT_SINK_STEP(1, 100), MOLTEN_HEAT_SINK_DURATION_TICKS(0, 72000),
        MOLTEN_HEAT_SINK_CAP(0, 40), MOLTEN_UNWIELDED_DECAY_INTERVAL_TICKS(0, 72000),
        MOLTEN_WHITE_HOT_FIRE_TICKS(0, 72000), MOLTEN_WHITE_HOT_DAMAGE_MULTIPLIER(0, 10),
        MOLTEN_OVERCLOCK_HEAT_FLOOR(0, 100), MOLTEN_OVERCLOCK_OUTGOING_MULTIPLIER(0, 10),
        MOLTEN_OVERCLOCK_INCOMING_AMPLIFICATION(0, 10), MOLTEN_HEAT_MAX(1, 100),
        MOLTEN_INCOMING_AMPLIFICATION_CAP(0, 10), MOLTEN_OUTGOING_BONUS_CAP(0, 10),
        MOLTEN_VENT_DRAIN(1, 100), MOLTEN_VENT_SPEED_MULTIPLIER(0, 16),
        MOLTEN_SHOCKWAVE_RADIUS(0, 64), MOLTEN_SHOCKWAVE_TARGET_CAP(0, 64),
        MOLTEN_SHOCKWAVE_KNOCKBACK_MULTIPLIER(0, 16), MOLTEN_BLAST_SPEED_TICKS(0, 72000),
        MOLTEN_RUPTURE_REFUND_TICKS(0, 72000), MOLTEN_RUPTURE_MIN_COOLDOWN_TICKS(1, 72000),
        MOLTEN_RUPTURE_SEEK_RANGE(0, 128), MOLTEN_RUPTURE_TURN_DEGREES(0, 180),
        MOLTEN_RECLAIM_TARGET_COUNT(1, 64), MOLTEN_RECLAIM_HEAT(0, 100),
        MOLTEN_AUTO_RUPTURE_INTERVAL_TICKS(1, 72000), MOLTEN_SHOCKWAVE_DAMAGE_MULTIPLIER(0, 10),
        MOLTEN_ROOT_SPEED_MULTIPLIER(0, 1), MOLTEN_RESISTANCE_AMPLIFIER(0, 10),
        MOLTEN_RUPTURE_LENGTH(0, 128), MOLTEN_RUPTURE_WIDTH(0, 64),
        MOLTEN_RUPTURE_SEGMENT_TARGET_CAP(0, 64), MOLTEN_RUPTURE_DAMAGE_MULTIPLIER(0, 10),
        MOLTEN_RUPTURE_KNOCK_UP(0, 16), MOLTEN_RUPTURE_FIRE_TICKS(0, 72000),
        MOLTEN_FORK_SWING_INTERVAL(1, 64), MOLTEN_FORK_COUNT(0, 64),
        MOLTEN_FORK_ANGLE_DEGREES(0, 180), MOLTEN_FORK_DAMAGE_MULTIPLIER(0, 10),
        MOLTEN_SEQUENCE_WINDOW_TICKS(0, 72000), MOLTEN_SEQUENCE_PER_STACK_MULTIPLIER(0, 10),
        MOLTEN_SEQUENCE_STACK_CAP(0, 64), MOLTEN_RUPTURE_COOLDOWN_MULTIPLIER(0, 10),
        MOLTEN_SHATTER_LANE_COUNT(0, 64), MOLTEN_SHATTER_LANE_LENGTH(0, 128),
        MOLTEN_SHATTER_LANE_ANGLE_DEGREES(0, 180), MOLTEN_SHATTER_DAMAGE_MULTIPLIER(0, 10),

        SOULPYRE_TETHER_DURATION_TICKS(1, 72000), SOULPYRE_START_RADIUS(0, 64),
        SOULPYRE_MAX_RADIUS(0, 64), SOULPYRE_PULSE_TARGET_CAP(0, 64),
        SOULPYRE_RADIUS_GROWTH(0, 16), SOULPYRE_PULSE_SOUL_MULTIPLIER(0, 10),
        SOULPYRE_BINDING_HIT_COUNT(1, 64), SOULPYRE_BINDING_WINDOW_TICKS(1, 72000),
        SOULPYRE_BINDING_SLOW_TICKS(0, 72000), SOULPYRE_BINDING_SLOW_AMPLIFIER(0, 10),
        SOULPYRE_PULL_INTERVAL(1, 64), SOULPYRE_PULL_STRENGTH(0, 16),
        SOULPYRE_FEAST_KILL_COUNT(1, 64), SOULPYRE_FEAST_ABSORPTION(0, 40),
        SOULPYRE_FEAST_ABSORPTION_TICKS(0, 72000), SOULPYRE_FEAST_ABSORPTION_CAP(0, 40),
        SOULPYRE_DEVOURING_EXTRA_PULSES(0, 64), SOULPYRE_DEVOURING_PULSE_DAMAGE_MULTIPLIER(0, 10),
        SOULPYRE_CLOSED_RADIUS(0, 64), SOULPYRE_CLOSED_PULSE_DAMAGE_MULTIPLIER(0, 10),
        SOULPYRE_CLOSED_INTERVAL_MULTIPLIER(0, 10),
        SOULPYRE_WISP_DAMAGE_MULTIPLIER(0, 10), SOULPYRE_WISP_VOLLEY_SIZE(1, 64),
        SOULPYRE_WISP_RANGE_BONUS(0, 128), SOULPYRE_WISP_SEARCH_CAP(0, 64),
        SOULPYRE_WISP_RETARGET_RANGE(0, 128), SOULPYRE_WISP_RETARGET_COUNT(0, 64),
        SOULPYRE_WISP_FIRE_TICKS(0, 72000), SOULPYRE_WISP_MARK_DURATION_TICKS(0, 72000),
        SOULPYRE_WISP_MARK_DAMAGE_MULTIPLIER(0, 10), SOULPYRE_WAILING_FULL_VOLLEY_COUNT(1, 64),
        SOULPYRE_WAILING_RADIUS(0, 64), SOULPYRE_WAILING_DAMAGE_MULTIPLIER(0, 10),
        SOULPYRE_WAILING_TARGET_CAP(0, 64), SOULPYRE_LEGION_VOLLEY_MULTIPLIER(0, 16),
        SOULPYRE_LEGION_DAMAGE_MULTIPLIER(0, 10), SOULPYRE_LEGION_PER_TARGET_CAP(1, 64),
        SOULPYRE_LANCE_DAMAGE_PER_SOUL(0, 10), SOULPYRE_LANCE_SOUL_CAP(1, 64),
        SOULPYRE_LANCE_TARGET_CAP(1, 64), SOULPYRE_DAMAGE_REDUCTION(0, 1),
        SOULPYRE_KNOCKBACK_LINGER_TICKS(0, 72000), SOULPYRE_FIRE_RESISTANCE_LINGER_TICKS(0, 72000),
        SOULPYRE_MANTLE_SOUL_STEP(1, 64), SOULPYRE_MANTLE_ABSORPTION(0, 40),
        SOULPYRE_MANTLE_ABSORPTION_CAP(0, 40), SOULPYRE_COLLAPSE_DURATION_TICKS(1, 72000),
        SOULPYRE_COLLAPSE_INTERVAL_TICKS(1, 72000), SOULPYRE_COLLAPSE_DAMAGE_MULTIPLIER(0, 10),
        SOULPYRE_REQUIEM_BONUS_PER_SOUL(0, 10), SOULPYRE_REQUIEM_SOUL_CAP(0, 64),
        SOULPYRE_LAST_RITES_SOUL_COUNT(1, 64), SOULPYRE_LAST_RITES_DURATION_TICKS(0, 72000),
        SOULPYRE_UNDYING_SOUL_COUNT(1, 64), SOULPYRE_UNDYING_RESISTANCE_AMPLIFIER(0, 10),
        SOULPYRE_UNDYING_RESISTANCE_TICKS(0, 72000), SOULPYRE_FUNERAL_DAMAGE_REDUCTION(0, 1),
        SOULPYRE_FUNERAL_RADIUS(0, 64), SOULPYRE_FUNERAL_DAMAGE_MULTIPLIER(0, 10),
        SOULPYRE_FUNERAL_TARGET_CAP(0, 64),

        HEARTH_IGNITE_TICKS(0, 72000), HEARTH_BRAND_ABSORPTION_DURATION_TICKS(0, 72000),
        HEARTH_BRAND_ABSORPTION_CAP(0, 40), HEARTH_FINAL_CHAIN_REQUIREMENT(0, 64),
        HEARTH_FINAL_CHAIN_MULTIPLIER(0, 10),

        EMBERBLADE_MIN_DAMAGE_MULTIPLIER(0, 10), EMBERBLADE_MAX_DAMAGE_MULTIPLIER(0, 10),
        EMBERBLADE_AIM_DAMAGE_MULTIPLIER(0, 10), EMBERBLADE_FULL_CHARGE_FIRE_TICKS(0, 72000),
        EMBERBLADE_CHANNEL_TICKS(1, 72000), EMBERBLADE_FULL_CHARGE_WINDOW_TICKS(0, 72000),
        EMBERBLADE_PIERCE_COUNT(0, 64), EMBERBLADE_PIERCE_RANGE(0, 128),
        EMBERBLADE_PIERCE_DAMAGE_MULTIPLIER(0, 10), EMBERBLADE_BANK_DURATION_TICKS(0, 72000),
        EMBERBLADE_BANK_MULTIPLIER(0, 1), EMBERBLADE_SPLASH_RADIUS(0, 64),
        EMBERBLADE_SPLASH_TARGET_CAP(0, 64), EMBERBLADE_SPLASH_DAMAGE_MULTIPLIER(0, 10),
        EMBERBLADE_RECOIL_DISTANCE(0, 16), EMBERBLADE_FALL_PROTECTION_TICKS(0, 72000),
        EMBERBLADE_QUICKDRAW_DURATION_TICKS(0, 72000), EMBERBLADE_HASTE_DURATION_TICKS(0, 72000),
        EMBERBLADE_MOVE_DISTANCE(0, 128), EMBERBLADE_NEXT_HIT_DURATION_TICKS(0, 72000),
        EMBERBLADE_NEXT_HIT_MULTIPLIER(0, 10), EMBERBLADE_LATE_GUARD_TICKS(0, 72000),
        EMBERBLADE_LATE_DAMAGE_REDUCTION(0, 1), EMBERBLADE_FULL_BUFF_LOCKOUT_TICKS(0, 72000),
        EMBERBLADE_IRE_RUSH_DURATION_TICKS(0, 72000), EMBERBLADE_PURSUIT_SPEED_TICKS(0, 72000),
        EMBERBLADE_BLASTBACK_RESISTANCE_TICKS(0, 72000), EMBERBLADE_IRE_DURATION_BONUS_TICKS(0, 72000),
        EMBERBLADE_INCARNATE_DURATION_TICKS(0, 72000),
        EMBERBLADE_FRAGMENT_COUNT(0, 64), EMBERBLADE_FRAGMENT_RANGE(0, 128),
        EMBERBLADE_FRAGMENT_DAMAGE_MULTIPLIER(0, 10), EMBERBLADE_FRAGMENT_SEEK_RANGE(0, 128),
        EMBERBLADE_FRAGMENT_SEEK_MULTIPLIER(0, 10), EMBERBLADE_FLASHOVER_COUNT(0, 64),
        EMBERBLADE_FLASHOVER_WINDOW_TICKS(0, 72000), EMBERBLADE_FLASHOVER_RADIUS(0, 64),
        EMBERBLADE_FLASHOVER_TARGET_CAP(0, 64), EMBERBLADE_FLASHOVER_DAMAGE_MULTIPLIER(0, 10),
        EMBERBLADE_BANK_GAIN(0, 1), EMBERBLADE_BANK_CAP(0, 1),
        EMBERBLADE_FRAGMENT_JUMP_RANGE(0, 128), EMBERBLADE_FRAGMENT_JUMP_MULTIPLIER(0, 10),

        EMBERLASH_SMOULDER_DAMAGE_MULTIPLIER(0, 10), EMBERLASH_SMOULDER_STACK_CAP(0, 64),
        EMBERLASH_SMOULDER_DURATION_TICKS(0, 72000), EMBERLASH_SWEEP_RADIUS(0, 64),
        EMBERLASH_SWEEP_TARGET_CAP(0, 64), EMBERLASH_COMBO_HITS(1, 64),
        EMBERLASH_COMBO_WINDOW_TICKS(0, 72000), EMBERLASH_MAX_DAMAGE_REDUCTION(0, 1),
        EMBERLASH_MAX_REDUCTION_DURATION_TICKS(0, 72000), EMBERLASH_EVADE_DISTANCE_MULTIPLIER(0, 16),
        EMBERLASH_CAUTERY_ABSORPTION(0, 40), EMBERLASH_CAUTERY_ABSORPTION_TICKS(0, 72000),
        EMBERLASH_BLIND_RADIUS(0, 64), EMBERLASH_BLIND_TARGET_CAP(0, 64),
        EMBERLASH_BLIND_DURATION_TICKS(0, 72000), EMBERLASH_BACKLASH_STACKS(0, 64),
        EMBERLASH_BACKLASH_DURATION_TICKS(0, 72000), EMBERLASH_EMERGENCY_LOCKOUT_TICKS(0, 72000),
        EMBERLASH_EMERGENCY_RESISTANCE_TICKS(0, 72000), EMBERLASH_PHOENIX_DAMAGE_MULTIPLIER(0, 10),
        EMBERLASH_PHOENIX_TARGET_CAP(0, 64), EMBERLASH_PHOENIX_FIRE_TICKS(0, 72000),
        EMBERLASH_HOT_BLOOD_LOCKOUT_TICKS(0, 72000), EMBERLASH_REPRISAL_DURATION_TICKS(0, 72000),
        EMBERLASH_REPRISAL_STACK_CAP(0, 64), EMBERLASH_REPRISAL_TRIGGER_COUNT(1, 64),
        EMBERLASH_REPRISAL_DAMAGE_MULTIPLIER(0, 10), EMBERLASH_ASH_RADIUS(0, 64),
        EMBERLASH_ASH_TARGET_CAP(0, 64), EMBERLASH_ASH_DAMAGE_PER_STACK(0, 10),
        EMBERLASH_ASH_APPLIED_STACKS(0, 64), EMBERLASH_BURNING_PACE_DURATION_TICKS(0, 72000),
        EMBERLASH_BURNING_PACE_AMPLIFIER(0, 10), EMBERLASH_LASHBACK_DURATION_TICKS(0, 72000),
        EMBERLASH_LASHBACK_AMPLIFIER(0, 10),
        EMBERLASH_KILL_REFUND_TICKS(0, 72000), EMBERLASH_DETONATION_DAMAGE_PER_STACK(0, 10),
        EMBERLASH_INCOMING_PER_CHARGE_MULTIPLIER(0, 10),

        MODE(0, Integer.MAX_VALUE);

        private final double minimum;
        private final double maximum;

        Setting(double minimum, double maximum) {
            this.minimum = minimum;
            this.maximum = maximum;
        }

        double validate(double value) {
            return Math.clamp(Double.isFinite(value) ? value : minimum, minimum, maximum);
        }
    }

    public static final Phase5AbilityTuning EMPTY = new Phase5AbilityTuning(Map.of());
    private final EnumMap<Setting, Double> values;

    private Phase5AbilityTuning(Map<Setting, Double> values) {
        this.values = new EnumMap<>(Setting.class);
        this.values.putAll(values);
    }

    public double get(Setting setting, double fallback) {
        return values.getOrDefault(setting, setting.validate(fallback));
    }

    public int integer(Setting setting, int fallback) {
        return (int) Math.round(get(setting, fallback));
    }

    public boolean has(Setting setting) {
        return values.containsKey(setting);
    }

    public boolean isEmpty() {
        return values.isEmpty();
    }

    public boolean flag(int bit) {
        return (integer(Setting.MODE, 0) & bit) != 0;
    }

    public Phase5AbilityTuning with(Setting setting, double value) {
        EnumMap<Setting, Double> updated = new EnumMap<>(values);
        updated.put(setting, setting.validate(value));
        return new Phase5AbilityTuning(updated);
    }

    public Phase5AbilityTuning add(Setting setting, double amount, double fallback) {
        return with(setting, get(setting, fallback) + amount);
    }

    public Phase5AbilityTuning multiply(Setting setting, double factor, double fallback) {
        return with(setting, get(setting, fallback) * factor);
    }
}
