package net.sweenus.simplyswords.api.ability;

import net.minecraft.nbt.NbtCompound;

import java.util.EnumMap;
import java.util.Map;

public final class Phase6AbilityTuning {
    public enum Setting {
        COOLDOWN_TICKS(0, 72000), DURATION_TICKS(0, 72000), INTERVAL_TICKS(1, 72000),
        LOCKOUT_TICKS(0, 72000), REFUND_TICKS(0, 72000), CHANCE(0, 100),
        DAMAGE_MULTIPLIER(0, 10), SECONDARY_DAMAGE_MULTIPLIER(0, 10), FINAL_DAMAGE_MULTIPLIER(0, 10),
        INCOMING_MULTIPLIER(0, 10), OUTGOING_MULTIPLIER(0, 10), PER_STACK_MULTIPLIER(0, 10),
        RADIUS(0, 64), RANGE(0, 128), WIDTH(0, 64), LENGTH(0, 128), SPEED(0, 16),
        PULL_STRENGTH(0, 16), KNOCKBACK(0, 16), TARGET_CAP(0, 64), SEARCH_CAP(0, 64),
        COUNT(0, 64), STACK_CAP(0, 64), CHARGE_CAP(0, 64), PULSE_COUNT(0, 64),
        FIRE_TICKS(0, 72000), FREEZE_TICKS(0, 72000), FREEZE_CAP_TICKS(0, 72000),
        STATUS_DURATION_TICKS(0, 72000),
        STATUS_AMPLIFIER(0, 10), ABSORPTION(0, 40), MODE(0, Integer.MAX_VALUE),

        STORMBRINGER_BLOCK_DURATION_TICKS(1, 72000), STORMBRINGER_PARRY_WINDOW_TICKS(1, 72000),
        STORMBRINGER_NORMAL_CHARGE_GAIN(0, 64), STORMBRINGER_PARRY_CHARGE_GAIN(0, 64),
        STORMBRINGER_CHARGE_GAIN_MULTIPLIER(0, 10), STORMBRINGER_CHARGE_CAP(1, 64),
        STORMBRINGER_COUNTER_DAMAGE_MULTIPLIER(0, 10), STORMBRINGER_COUNTER_RADIUS(0, 64),
        STORMBRINGER_COUNTER_TARGET_CAP(1, 64), STORMBRINGER_BLOCK_RESISTANCE_TICKS(0, 72000),
        STORMBRINGER_COUNTER_KNOCKBACK_MULTIPLIER(0, 16), STORMBRINGER_COUNTER_FIRE_TICKS(0, 72000),
        STORMBRINGER_ACTIVE_REFUND_TICKS(0, 72000), STORMBRINGER_FREE_CHAIN_LOCKOUT_TICKS(0, 72000),
        STORMBRINGER_MELEE_CHARGE_THRESHOLD(0, 64), STORMBRINGER_MELEE_DAMAGE_MULTIPLIER(0, 10),
        STORMBRINGER_OVERFLOW_ABSORPTION(0, 40), STORMBRINGER_OVERFLOW_DURATION_TICKS(0, 72000),
        STORMBRINGER_OVERFLOW_LOCKOUT_TICKS(0, 72000), STORMBRINGER_RESIDUAL_SLOW_TICKS(0, 72000),
        STORMBRINGER_RHYTHM_SPEND_COUNT(0, 64), STORMBRINGER_RHYTHM_WINDOW_TICKS(0, 72000),
        STORMBRINGER_RHYTHM_HASTE_TICKS(0, 72000), STORMBRINGER_FULL_DAMAGE_MULTIPLIER(0, 10),
        STORMBRINGER_FULL_CHARGE_COST(0, 64), STORMBRINGER_SUPERCELL_DAMAGE_PER_CHARGE(0, 10),
        STORMBRINGER_SUPERCELL_DECAY_TICKS(0, 72000), STORMBRINGER_CHAIN_COOLDOWN_MULTIPLIER(0, 10),
        STORMBRINGER_CHAIN_RANGE(0, 128), STORMBRINGER_CHAIN_DAMAGE_MULTIPLIER(0, 10),
        STORMBRINGER_FORK_EXTRA_TARGETS(0, 64), STORMBRINGER_MARK_DURATION_TICKS(0, 72000),
        STORMBRINGER_MARK_DAMAGE_MULTIPLIER(0, 10), STORMBRINGER_BURST_RADIUS(0, 64),
        STORMBRINGER_BURST_DAMAGE_MULTIPLIER(0, 10), STORMBRINGER_BURST_TARGET_CAP(0, 64),
        STORMBRINGER_KILL_REFUND_CAP(0, 64), STORMBRINGER_CADENCE_REFUND_PER_TARGET(0, 72000),
        STORMBRINGER_CADENCE_MIN_COOLDOWN_TICKS(0, 72000), STORMBRINGER_FOCUSED_HIT_COUNT(0, 64),
        STORMBRINGER_FOCUSED_HIT_DAMAGE_MULTIPLIER(0, 10), STORMBRINGER_ROLLING_TARGET_CAP(0, 64),
        STORMBRINGER_ROLLING_RANGE_BONUS(0, 128), STORMBRINGER_ROLLING_JUMP_MULTIPLIER(0, 10),

        MJOLNIR_DURATION_TICKS(0, 72000), MJOLNIR_DURATION_BONUS_TICKS(0, 72000),
        MJOLNIR_DURATION_MULTIPLIER(0, 10), MJOLNIR_PULSE_INTERVAL_TICKS(1, 72000),
        MJOLNIR_STORM_RADIUS_BONUS(0, 64), MJOLNIR_STORM_RADIUS_MULTIPLIER(0, 10),
        MJOLNIR_STORM_TARGET_CAP(0, 64), MJOLNIR_BOLT_DAMAGE_MULTIPLIER(0, 10),
        MJOLNIR_CONDUCTIVE_DURATION_TICKS(0, 72000), MJOLNIR_CONDUCTIVE_BONUS_TICKS(0, 72000),
        MJOLNIR_FORK_COUNT(0, 64),
        MJOLNIR_FORK_RANGE(0, 128), MJOLNIR_FORK_DAMAGE_MULTIPLIER(0, 10),
        MJOLNIR_FINALE_PER_TARGET_MULTIPLIER(0, 10), MJOLNIR_FINALE_TARGET_CAP(0, 64),
        MJOLNIR_FINAL_BOLT_COUNT(0, 64), MJOLNIR_FINAL_RADIUS_BONUS(0, 64),
        MJOLNIR_FINAL_TARGET_CAP(0, 64), MJOLNIR_FINAL_DAMAGE_MULTIPLIER(0, 10),
        MJOLNIR_FINAL_KNOCKBACK_MULTIPLIER(0, 16), MJOLNIR_BURST_KNOCKBACK_MULTIPLIER(0, 16),
        MJOLNIR_BURST_KNOCKUP_MULTIPLIER(0, 16), MJOLNIR_SPEED_DURATION_TICKS(0, 72000),
        MJOLNIR_SPEED_AMPLIFIER(0, 10), MJOLNIR_ENTRY_RADIUS(0, 64),
        MJOLNIR_ENTRY_DAMAGE_MULTIPLIER(0, 10), MJOLNIR_ENTRY_LOCKOUT_TICKS(0, 72000),
        MJOLNIR_ADVANCE_DISTANCE(0, 128), MJOLNIR_ADVANCE_DAMAGE_MULTIPLIER(0, 10),
        MJOLNIR_RECALL_ARM_TICKS(0, 72000), MJOLNIR_WAKE_RADIUS(0, 64),
        MJOLNIR_WAKE_TARGET_CAP(0, 64), MJOLNIR_WAKE_DAMAGE_MULTIPLIER(0, 10),
        MJOLNIR_WAKE_LOCKOUT_TICKS(0, 72000), MJOLNIR_SKYBOUND_DURATION_TICKS(0, 72000),
        MJOLNIR_SKYBOUND_AMPLIFIER(0, 10), MJOLNIR_FLASH_SPEED_TICKS(0, 72000),
        MJOLNIR_FLASH_SPEED_AMPLIFIER(0, 10), MJOLNIR_FLASH_REFUND_TICKS(0, 72000),
        MJOLNIR_RIDE_RESISTANCE_TICKS(0, 72000), MJOLNIR_ANCHOR_RADIUS(0, 64),
        MJOLNIR_SHELL_ABSORPTION(0, 40), MJOLNIR_SHELL_DURATION_TICKS(0, 72000),
        MJOLNIR_CONDUCTIVE_INCOMING_MULTIPLIER(0, 10), MJOLNIR_REBUKE_DAMAGE_MULTIPLIER(0, 10),
        MJOLNIR_REBUKE_LOCKOUT_TICKS(0, 72000), MJOLNIR_SHELTER_AMPLIFIER(0, 10),
        MJOLNIR_AEGIS_ABSORPTION(0, 40), MJOLNIR_AEGIS_DURATION_TICKS(0, 72000),
        MJOLNIR_AEGIS_AMPLIFIER(0, 10),

        THUNDERBRAND_REFRESH_CHANCE_BONUS(0, 100), THUNDERBRAND_COOLDOWN_REDUCTION_TICKS(0, 72000),
        THUNDERBRAND_CHARGE_REDUCTION_TICKS(0, 72000), THUNDERBRAND_DASH_BONUS_TICKS(0, 72000),
        THUNDERBRAND_DASH_DURATION_MULTIPLIER(0, 10), THUNDERBRAND_DASH_DURATION_TICKS(0, 72000),
        THUNDERBRAND_DASH_SPEED_MULTIPLIER(0, 10), THUNDERBRAND_COLLISION_RADIUS_BONUS(0, 64),
        THUNDERBRAND_COLLISION_DAMAGE_MULTIPLIER(0, 10), THUNDERBRAND_BURST_DAMAGE_MULTIPLIER(0, 10),
        THUNDERBRAND_STEERING_MULTIPLIER(0, 10), THUNDERBRAND_BLITZ_BURST_RADIUS(0, 64),
        THUNDERBRAND_BLITZ_BURST_DAMAGE_MULTIPLIER(0, 10), THUNDERBRAND_BLITZ_BURST_TARGET_CAP(0, 64),
        THUNDERBRAND_DEFENSE_PADDING_TICKS(0, 72000), THUNDERBRAND_MEMORY_TICKS(0, 72000),
        THUNDERBRAND_STORED_HIT_CAP(0, 64), THUNDERBRAND_ABSORPTION_PER_HIT(0, 40),
        THUNDERBRAND_ABSORPTION_CAP(0, 40), THUNDERBRAND_ABSORPTION_DURATION_TICKS(0, 72000),
        THUNDERBRAND_RETALIATORY_SLOW_TICKS(0, 72000), THUNDERBRAND_OVERLOAD_THRESHOLD(0, 64),
        THUNDERBRAND_OVERLOAD_DAMAGE_MULTIPLIER(0, 10), THUNDERBRAND_CAP_REFUND_TICKS(0, 72000),
        THUNDERBRAND_GROUNDED_DAMAGE_PER_HIT(0, 10), THUNDERBRAND_INSULATOR_DAMAGE_MULTIPLIER(0, 10),
        THUNDERBRAND_CHAIN_EXTRA_TARGETS(0, 64), THUNDERBRAND_CHAIN_TARGET_CAP(0, 64),
        THUNDERBRAND_CHAIN_RANGE_BONUS(0, 128), THUNDERBRAND_CHAIN_DAMAGE_MULTIPLIER(0, 10),
        THUNDERBRAND_CONDUCTOR_DAMAGE_MULTIPLIER(0, 10), THUNDERBRAND_CONDUCTOR_DURATION_TICKS(0, 72000),
        THUNDERBRAND_CROSSCURRENT_DAMAGE_MULTIPLIER(0, 10), THUNDERBRAND_ARC_WAKE_RADIUS(0, 64),
        THUNDERBRAND_ARC_WAKE_DAMAGE_MULTIPLIER(0, 10), THUNDERBRAND_ARC_WAKE_TARGET_CAP(0, 64),
        THUNDERBRAND_FINAL_RADIUS(0, 64), THUNDERBRAND_FINAL_DAMAGE_MULTIPLIER(0, 10),
        THUNDERBRAND_FINAL_TARGET_CAP(0, 64), THUNDERBRAND_RAIL_DAMAGE_PER_HIT(0, 10),
        THUNDERBRAND_RAIL_HIT_CAP(0, 64), THUNDERBRAND_WEB_CHAIN_COUNT(0, 64),
        THUNDERBRAND_WEB_DAMAGE_MULTIPLIER(0, 10),

        TEMPEST_START_RADIUS_BONUS(0, 64), TEMPEST_RADIUS_PER_STACK_MULTIPLIER(0, 10),
        TEMPEST_VORTEX_DAMAGE_MULTIPLIER(0, 10), TEMPEST_VORTEX_PULL_STRENGTH(0, 16),
        TEMPEST_SHELL_STACK_THRESHOLD(0, 64), TEMPEST_SHELL_ABSORPTION(0, 40),
        TEMPEST_SHELL_DURATION_TICKS(0, 72000), TEMPEST_DURATION_BONUS_TICKS(0, 72000),
        TEMPEST_SHRINK_INTERVAL_MULTIPLIER(0, 10), TEMPEST_MAX_SIZE_MULTIPLIER(0, 10),
        TEMPEST_MAX_CADENCE_INTERVAL_TICKS(1, 72000), TEMPEST_PULSE_TARGET_CAP(1, 64),
        TEMPEST_SPEED_AMPLIFIER(0, 10), TEMPEST_FIXED_RANGE(0, 128),
        TEMPEST_MARK_DURATION_BONUS_TICKS(0, 72000), TEMPEST_MARK_STACK_CAP(1, 64),
        TEMPEST_SHIFTING_ATTACK_COUNT(0, 64), TEMPEST_FIRE_DAMAGE_MULTIPLIER(0, 10),
        TEMPEST_FROST_SLOW_BONUS(0, 1), TEMPEST_FROST_SLOW_CAP(0, 1),
        TEMPEST_BALANCED_ATTACK_COUNT(0, 64), TEMPEST_SEQUENCE_WINDOW_TICKS(0, 72000),
        TEMPEST_SEQUENCE_HASTE_TICKS(0, 72000), TEMPEST_SEQUENCE_HASTE_AMPLIFIER(0, 10),
        TEMPEST_SPECIALIST_LOCK_TICKS(0, 72000), TEMPEST_SPECIALIST_POTENCY_MULTIPLIER(0, 10),
        TEMPEST_PRISMATIC_STACK_CAP(1, 64), TEMPEST_PRISMATIC_DAMAGE_MULTIPLIER(0, 10),
        TEMPEST_RECALL_RETAIN_COUNT(0, 64), TEMPEST_CONSUMED_DAMAGE_PER_STACK(0, 10),
        TEMPEST_THERMAL_RADIUS(0, 64), TEMPEST_THERMAL_DAMAGE_MULTIPLIER(0, 10),
        TEMPEST_THERMAL_TARGET_CAP(1, 64), TEMPEST_RIME_STACK_THRESHOLD(0, 64),
        TEMPEST_RIME_HIT_COUNT(0, 64), TEMPEST_RIME_ROOT_TICKS(0, 72000),
        TEMPEST_STEAM_PULSE_COUNT(0, 64), TEMPEST_STEAM_RADIUS(0, 64),
        TEMPEST_STEAM_DAMAGE_MULTIPLIER(0, 10), TEMPEST_STEAM_TARGET_CAP(1, 64),
        TEMPEST_RESISTANCE_AMPLIFIER(0, 10), TEMPEST_FINAL_DAMAGE_PER_STACK(0, 10),
        TEMPEST_FINAL_STACK_CAP(0, 64), TEMPEST_FINAL_RADIUS(0, 64),
        TEMPEST_FINAL_TARGET_CAP(1, 64), TEMPEST_SINGULARITY_RADIUS(0, 64),
        TEMPEST_SINGULARITY_PULL_MULTIPLIER(0, 16), TEMPEST_SINGULARITY_DAMAGE_MULTIPLIER(0, 10),
        TEMPEST_SINGULARITY_DURATION_MULTIPLIER(0, 10), TEMPEST_WAVE_COUNT(0, 64),
        TEMPEST_WAVE_DAMAGE_MULTIPLIER(0, 10), TEMPEST_WAVE_WIDTH(0, 64),
        TEMPEST_WAVE_TARGET_CAP(1, 64),

        FROSTFALL_DIRECT_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_DIRECT_SLOW_TICKS(0, 72000),
        FROSTFALL_HIGH_ARC_FLIGHT_TICKS(0, 72000), FROSTFALL_HIGH_ARC_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_SLOWED_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_DIRECT_FREEZE_TICKS(0, 72000),
        FROSTFALL_SPLINTER_COUNT(0, 64), FROSTFALL_SPLINTER_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_SPLINTER_RANGE(0, 128), FROSTFALL_MARK_RANGE(0, 128),
        FROSTFALL_MARK_DURATION_TICKS(0, 72000), FROSTFALL_MARK_PULSE_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_DEADFALL_ANGLE_DEGREES(0, 90), FROSTFALL_DEADFALL_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_DEADFALL_PULSE_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_COOLDOWN_MULTIPLIER(0, 10),
        FROSTFALL_SKIRMISHER_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_RETURN_SPEED_MULTIPLIER(0, 16),
        FROSTFALL_RETURN_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_RETURN_TARGET_CAP(0, 64),
        FROSTFALL_RETURN_PULL_STRENGTH(0, 16), FROSTFALL_CATCH_SPEED_TICKS(0, 72000),
        FROSTFALL_CATCH_SPEED_AMPLIFIER(0, 10), FROSTFALL_CATCH_REFUND_TICKS(0, 72000),
        FROSTFALL_RETURN_ROOT_TICKS(0, 72000), FROSTFALL_PERFECT_RETURN_WINDOW_TICKS(0, 72000),
        FROSTFALL_PERFECT_RETURN_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_PERFECT_RETURN_DURATION_TICKS(0, 72000),
        FROSTFALL_ORBIT_RADIUS(0, 64), FROSTFALL_ORBIT_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_ORBIT_DURATION_TICKS(0, 72000), FROSTFALL_RECALL_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_PULSE_RADIUS_BONUS(0, 64), FROSTFALL_PULSE_TARGET_CAP(1, 64),
        FROSTFALL_PULSE_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_PULSE_SLOW_BONUS_TICKS(0, 72000),
        FROSTFALL_PULSE_PULL_MULTIPLIER(0, 16), FROSTFALL_SPIKE_PULSE_INDEX(1, 64),
        FROSTFALL_SPIKE_COUNT(0, 64), FROSTFALL_SPIKE_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_PERMAFROST_DURATION_TICKS(0, 72000), FROSTFALL_PERMAFROST_AMPLIFIER(0, 10),
        FROSTFALL_SHATTER_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_FIELD_PULSE_COUNT(0, 64),
        FROSTFALL_FIELD_DURATION_TICKS(0, 72000), FROSTFALL_AVALANCHE_DAMAGE_MULTIPLIER(0, 10),
        FROSTFALL_AVALANCHE_PULL_MULTIPLIER(0, 16), FROSTFALL_GLACIER_DELAY_TICKS(0, 72000),
        FROSTFALL_GLACIER_DAMAGE_MULTIPLIER(0, 10), FROSTFALL_GLACIER_PULL_MULTIPLIER(0, 16),

        ICEWHISPER_AURA_DAMAGE_MULTIPLIER(0, 10), ICEWHISPER_AURA_RADIUS_BONUS(0, 64),
        ICEWHISPER_AURA_RADIUS_MULTIPLIER(0, 10), ICEWHISPER_AURA_TARGET_CAP(0, 64),
        ICEWHISPER_AURA_SLOW_BONUS_TICKS(0, 72000), ICEWHISPER_AURA_AMPLIFIER_CAP(0, 10),
        ICEWHISPER_AURA_INCOMING_MULTIPLIER(0, 10), ICEWHISPER_SLOW_RADIUS(0, 64),
        ICEWHISPER_INNER_RADIUS(0, 64), ICEWHISPER_INNER_AMPLIFIER(0, 10),
        ICEWHISPER_DWELL_TICKS(0, 72000), ICEWHISPER_DWELL_DAMAGE_MULTIPLIER(0, 10),
        ICEWHISPER_DWELL_LOCKOUT_TICKS(0, 72000), ICEWHISPER_FREEZE_PER_PULSE_TICKS(0, 72000),
        ICEWHISPER_FREEZE_CAP_TICKS(0, 72000), ICEWHISPER_FROZEN_THRESHOLD_TICKS(0, 72000),
        ICEWHISPER_FROZEN_DAMAGE_MULTIPLIER(0, 10), ICEWHISPER_SLOW_ATTACK_MULTIPLIER(0, 10),
        ICEWHISPER_SLOW_ATTACK_TICKS(0, 72000), ICEWHISPER_PROJECTILE_INCOMING_MULTIPLIER(0, 10),
        ICEWHISPER_STORM_RADIUS_BONUS(0, 64), ICEWHISPER_STORM_RADIUS_MULTIPLIER(0, 10),
        ICEWHISPER_STORM_DURATION_BONUS_TICKS(0, 72000), ICEWHISPER_WAVE_INTERVAL_TICKS(1, 72000),
        ICEWHISPER_FALL_REDUCTION_TICKS(0, 72000), ICEWHISPER_COMET_COUNT(0, 64),
        ICEWHISPER_COMET_COUNT_MULTIPLIER(0, 10), ICEWHISPER_EXTRA_COMET_WAVE_INTERVAL(1, 64),
        ICEWHISPER_EXTRA_COMET_COUNT(0, 64), ICEWHISPER_COMET_DAMAGE_MULTIPLIER(0, 10),
        ICEWHISPER_SPLASH_RADIUS(0, 64), ICEWHISPER_SPLASH_RADIUS_BONUS(0, 64),
        ICEWHISPER_SPLASH_TARGET_CAP(0, 64), ICEWHISPER_HUNTER_RANGE(0, 128),
        ICEWHISPER_HUNTER_COMET_COUNT(0, 64), ICEWHISPER_FRACTURE_WINDOW_TICKS(0, 72000),
        ICEWHISPER_FRACTURE_PER_STACK_MULTIPLIER(0, 10), ICEWHISPER_FRACTURE_STACK_CAP(0, 64),
        ICEWHISPER_BLIND_TICKS(0, 72000), ICEWHISPER_WARD_ABSORPTION(0, 40),
        ICEWHISPER_WARD_DURATION_TICKS(0, 72000), ICEWHISPER_STEP_RADIUS(0, 64),
        ICEWHISPER_STEP_SPEED_TICKS(0, 72000), ICEWHISPER_STEP_SPEED_AMPLIFIER(0, 10),
        ICEWHISPER_REBUKE_FREEZE_TICKS(0, 72000), ICEWHISPER_REBUKE_LOCKOUT_TICKS(0, 72000),
        ICEWHISPER_LAST_SNOW_HEALTH_PERCENT(0, 100), ICEWHISPER_LAST_SNOW_RESISTANCE_TICKS(0, 72000),
        ICEWHISPER_LAST_SNOW_AMPLIFIER(0, 10), ICEWHISPER_GLOBE_RESISTANCE_TICKS(0, 72000),
        ICEWHISPER_GLOBE_AMPLIFIER(0, 10), ICEWHISPER_BLACK_ICE_MULTIPLIER(0, 10),

        LIVYATAN_WAVE_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_WAVE_WIDTH_BONUS(0, 64),
        LIVYATAN_WAVE_LENGTH_BONUS_STEPS(0, 128), LIVYATAN_WAVE_KNOCKBACK_MULTIPLIER(0, 16),
        LIVYATAN_WAVE_FINAL_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_WAVE_SLOW_TICKS(0, 72000),
        LIVYATAN_DOUBLE_SWING_COUNT(0, 64), LIVYATAN_DOUBLE_DELAY_TICKS(0, 72000),
        LIVYATAN_DOUBLE_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_WALL_WIDTH_BONUS(0, 64),
        LIVYATAN_WALL_TARGET_CAP(0, 64), LIVYATAN_WALL_DAMAGE_MULTIPLIER(0, 10),
        LIVYATAN_WALL_KNOCKBACK_MULTIPLIER(0, 16), LIVYATAN_LANCE_WIDTH(0, 64),
        LIVYATAN_LANCE_LENGTH_MULTIPLIER(0, 10), LIVYATAN_LANCE_DAMAGE_MULTIPLIER(0, 10),
        LIVYATAN_LANCE_KNOCKBACK_MULTIPLIER(0, 16), LIVYATAN_RETURN_SPEED_MULTIPLIER(0, 16),
        LIVYATAN_RETURN_PULL_MULTIPLIER(0, 16), LIVYATAN_RETURN_RADIUS_BONUS(0, 64),
        LIVYATAN_RETURN_LIGHTNING_CHANCE_BONUS(0, 100), LIVYATAN_RETURN_LIGHTNING_DAMAGE_MULTIPLIER(0, 10),
        LIVYATAN_RETURN_ROOT_DISTANCE(0, 64), LIVYATAN_RETURN_ROOT_TICKS(0, 72000),
        LIVYATAN_CATCH_HIT_THRESHOLD(0, 64), LIVYATAN_CATCH_REFUND_TICKS(0, 72000),
        LIVYATAN_MAELSTROM_ROTATIONS(0, 64), LIVYATAN_MAELSTROM_DURATION_TICKS(0, 72000),
        LIVYATAN_MAELSTROM_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_MAELSTROM_PULL_MULTIPLIER(0, 16),
        LIVYATAN_THUNDERHEAD_LIGHTNING_MULTIPLIER(0, 10), LIVYATAN_THUNDERHEAD_TARGET_CAP(0, 64),
        LIVYATAN_THROW_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_SPLASH_RADIUS(0, 64),
        LIVYATAN_SPLASH_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_SPLASH_TARGET_CAP(0, 64),
        LIVYATAN_CONDUCTION_RANGE(0, 128), LIVYATAN_CONDUCTION_DAMAGE_MULTIPLIER(0, 10),
        LIVYATAN_CONDUCTION_TARGET_COUNT(0, 64), LIVYATAN_STEERING_RANGE(0, 128),
        LIVYATAN_STEERING_DEGREES(0, 180), LIVYATAN_SURGE_HIT_COUNT(0, 64),
        LIVYATAN_SURGE_WINDOW_TICKS(0, 72000), LIVYATAN_SURGE_DAMAGE_MULTIPLIER(0, 10),
        LIVYATAN_MARK_DURATION_TICKS(0, 72000), LIVYATAN_MARK_WAVE_DAMAGE_MULTIPLIER(0, 10),
        LIVYATAN_PERFECT_STORM_WINDOW_TICKS(0, 72000), LIVYATAN_PERFECT_STORM_RADIUS(0, 64),
        LIVYATAN_PERFECT_STORM_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_PERFECT_STORM_TARGET_CAP(0, 64),
        LIVYATAN_UNBOUND_WAVE_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_UNBOUND_COOLDOWN_MULTIPLIER(0, 10),
        LIVYATAN_CALM_DAMAGE_MULTIPLIER(0, 10), LIVYATAN_ACTIVE_COOLDOWN_BONUS_TICKS(0, 72000),
        LIVYATAN_SUPPRESS_WAVES(0, 1);

        private final double minimum;
        private final double maximum;

        Setting(double minimum, double maximum) {
            this.minimum = minimum;
            this.maximum = maximum;
        }

        double validate(double value) {
            return Math.clamp(Double.isFinite(value) ? value : minimum, minimum, maximum);
        }
    }

    public static final Phase6AbilityTuning EMPTY = new Phase6AbilityTuning(Map.of());
    private final EnumMap<Setting, Double> values;

    private Phase6AbilityTuning(Map<Setting, Double> values) {
        this.values = new EnumMap<>(Setting.class);
        this.values.putAll(values);
    }

    public double get(Setting setting, double fallback) {
        return values.getOrDefault(setting, setting.validate(fallback));
    }

    public int integer(Setting setting, int fallback) {
        return (int) Math.round(get(setting, fallback));
    }

    public boolean has(Setting setting) {
        return values.containsKey(setting);
    }

    public boolean flag(int bit) {
        return (integer(Setting.MODE, 0) & bit) != 0;
    }

    public Phase6AbilityTuning with(Setting setting, double value) {
        EnumMap<Setting, Double> updated = new EnumMap<>(values);
        updated.put(setting, setting.validate(value));
        return new Phase6AbilityTuning(updated);
    }

    public Phase6AbilityTuning add(Setting setting, double amount, double fallback) {
        return with(setting, get(setting, fallback) + amount);
    }

    public Phase6AbilityTuning multiply(Setting setting, double factor, double fallback) {
        return with(setting, get(setting, fallback) * factor);
    }

    public NbtCompound toNbt() {
        NbtCompound nbt = new NbtCompound();
        values.forEach((setting, value) -> nbt.putDouble(setting.name(), value));
        return nbt;
    }

    public static Phase6AbilityTuning fromNbt(NbtCompound nbt) {
        if (nbt == null || nbt.isEmpty()) return EMPTY;
        Phase6AbilityTuning tuning = EMPTY;
        for (Setting setting : Setting.values()) {
            if (nbt.contains(setting.name())) tuning = tuning.with(setting, nbt.getDouble(setting.name()));
        }
        return tuning;
    }
}
