package net.sweenus.simplyswords.api.ability;

import java.util.EnumMap;
import java.util.Map;

public final class Phase7AbilityTuning {
    public enum Setting {
        COOLDOWN_TICKS(0, 72000), DURATION_TICKS(0, 72000), INTERVAL_TICKS(1, 72000),
        LOCKOUT_TICKS(0, 72000), REFUND_TICKS(0, 72000), CHANCE(0, 100),
        DAMAGE_MULTIPLIER(0, 10), SECONDARY_DAMAGE_MULTIPLIER(0, 10), FINAL_DAMAGE_MULTIPLIER(0, 10),
        INCOMING_MULTIPLIER(0, 10), OUTGOING_MULTIPLIER(0, 10), PER_STACK_MULTIPLIER(0, 10),
        RADIUS(0, 64), RANGE(0, 128), WIDTH(0, 64), SPEED(0, 16), PULL_STRENGTH(0, 16),
        TARGET_CAP(0, 64), SEARCH_CAP(0, 64), COUNT(0, 64), STACK_CAP(0, 64),
        FIRE_TICKS(0, 72000), STATUS_DURATION_TICKS(0, 72000), STATUS_AMPLIFIER(0, 10),
        ABSORPTION(0, 40), HEALTH_THRESHOLD(0, 1), MODE(0, Integer.MAX_VALUE),
        BRAMBLE_GRASP_RANGE_BONUS(0, 128), BRAMBLE_GRASP_RADIUS_BONUS(0, 64),
        BRAMBLE_GRASP_TRAVEL_TICK_BONUS(-72000, 72000),
        BRAMBLE_BIND_DURATION_BONUS_TICKS(0, 72000), BRAMBLE_PULL_MULTIPLIER(0, 16),
        BRAMBLE_SHARED_DAMAGE_RATIO(0, 1), BRAMBLE_SLAM_DAMAGE_MULTIPLIER(0, 10),
        BRAMBLE_LIFT_FORCE_MULTIPLIER(0, 16),
        BRAMBLE_TANGLED_TARGET_CAP(0, 64), BRAMBLE_TANGLED_SHARED_DAMAGE_RATIO(0, 1),
        BRAMBLE_TANGLED_DISABLE_PULL(0, 1), BRAMBLE_TANGLED_DISABLE_SLAM(0, 1),
        BRAMBLE_HANGMAN_TARGET_CAP(0, 64), BRAMBLE_HANGMAN_LIFT_FORCE_MULTIPLIER(0, 16),
        BRAMBLE_HANGMAN_SLAM_DAMAGE_MULTIPLIER(0, 10),
        BRAMBLE_HUNT_MEMORY_BONUS_TICKS(0, 72000),
        BRAMBLE_HUNT_COOLDOWN_BONUS_TICKS(-72000, 72000),
        BRAMBLE_HUNT_RANGE_BONUS(0, 128), BRAMBLE_HUNT_WIDTH_BONUS(0, 64),
        BRAMBLE_HUNT_DAMAGE_MULTIPLIER(0, 10),
        BRAMBLE_HUNT_SLOW_DURATION_BONUS_TICKS(0, 72000),
        BRAMBLE_HUNT_MIN_SLOW_AMPLIFIER(0, 10), BRAMBLE_HUNT_PATH_TARGET_CAP(0, 64),
        BRAMBLE_CROSSCUT_TARGET_COUNT(0, 64), BRAMBLE_CROSSCUT_WINDOW_TICKS(0, 72000),
        BRAMBLE_CROSSCUT_DAMAGE_MULTIPLIER(0, 10),
        BRAMBLE_WALTZ_PROJECTILE_COUNT(0, 64), BRAMBLE_WALTZ_DAMAGE_MULTIPLIER(0, 10),
        BRAMBLE_WALTZ_DISABLE_SLOW(0, 1), BRAMBLE_PREDATOR_TARGET_ONLY(0, 1),
        BRAMBLE_PREDATOR_DAMAGE_MULTIPLIER(0, 10), BRAMBLE_PREDATOR_MEMORY_TICKS(0, 72000),
        BRAMBLE_BARKSKIN_ABSORPTION(0, 40), BRAMBLE_BARKSKIN_DURATION_TICKS(0, 72000),
        BRAMBLE_ROOTED_GUARD_TARGET_COUNT(0, 64),
        BRAMBLE_ROOTED_GUARD_INCOMING_MULTIPLIER(0, 10),
        BRAMBLE_RETORT_DAMAGE_MULTIPLIER(0, 10), BRAMBLE_RETORT_LOCKOUT_TICKS(0, 72000),
        BRAMBLE_SAP_RISE_ABSORPTION(0, 40), BRAMBLE_SAP_RISE_CAP(0, 40),
        BRAMBLE_SHELTERWOOD_OUTGOING_MULTIPLIER(0, 10),
        BRAMBLE_THORNWARD_TARGET_COUNT(0, 64), BRAMBLE_THORNWARD_DURATION_TICKS(0, 72000),
        BRAMBLE_THORNWARD_AMPLIFIER(0, 10), BRAMBLE_RECLAIMED_REFUND_TICKS(0, 72000),
        BRAMBLE_RECLAIMED_REFUND_CAP_TICKS(0, 72000),
        BRAMBLE_ANCIENT_BIND_DURATION_MULTIPLIER(0, 10),
        BRAMBLE_ANCIENT_SHARED_DAMAGE_MULTIPLIER(0, 10),
        BRAMBLE_ANCIENT_RESISTANCE_AMPLIFIER(0, 10),
        BRAMBLE_BRIAR_RADIUS(0, 64), BRAMBLE_BRIAR_DAMAGE_MULTIPLIER(0, 10),
        BRAMBLE_BRIAR_TARGET_CAP(0, 64),
        WAX_PRISON_RANGE_BONUS(0, 128), WAX_PRISON_DURATION_BONUS_TICKS(0, 72000),
        WAX_TAUNT_RADIUS_BONUS(0, 64), WAX_TAUNT_INTERVAL_BONUS_TICKS(-72000, 72000),
        WAX_EXPLOSION_DAMAGE_MULTIPLIER(0, 10), WAX_EXPLOSION_FIRE_BONUS_TICKS(0, 72000),
        WAX_EXPLOSION_RADIUS_BONUS(0, 64), WAX_BRITTLE_DAMAGE_PER_STEP(0, 10),
        WAX_BRITTLE_DURATION_REDUCTION_TICKS(0, 72000), WAX_IRON_DURATION_TICKS(0, 72000),
        WAX_IRON_DAMAGE_MULTIPLIER(0, 10), WAX_IRON_OUTGOING_MULTIPLIER(0, 10),
        WAX_VOLATILE_DURATION_TICKS(0, 72000), WAX_VOLATILE_DAMAGE_MULTIPLIER(0, 10),
        WAX_VOLATILE_TAUNT_RADIUS_MULTIPLIER(0, 10),
        WAX_TEMPO_DURATION_BONUS_TICKS(0, 72000), WAX_TEMPO_STACK_CAP(0, 64),
        WAX_ENCASED_FIRE_TICKS(0, 72000), WAX_RHYTHM_SPEED_BONUS(0, 16),
        WAX_REFUND_PER_HIT_TICKS(0, 72000), WAX_REFUND_CAP_TICKS(0, 72000),
        WAX_REFUND_WINDOW_TICKS(0, 72000), WAX_CANDLE_STEP_TICKS(0, 72000),
        WAX_FLASH_MULTIPLIER(0, 10), WAX_FLASH_WINDOW_TICKS(0, 72000),
        WAX_FRENZY_BONUS_MULTIPLIER(0, 10), WAX_FRENZY_DURATION_TICKS(0, 72000),
        WAX_PATIENT_DURATION_TICKS(0, 72000),
        WAX_REVIVE_RESISTANCE_BONUS_TICKS(0, 72000),
        WAX_REVIVE_COOLDOWN_BONUS_TICKS(-72000, 72000),
        WAX_FIRST_LAYER_ABSORPTION(0, 40), WAX_FIRST_LAYER_DURATION_TICKS(0, 72000),
        WAX_REACTIVE_HEALTH_THRESHOLD(0, 1), WAX_REACTIVE_DURATION_TICKS(0, 72000),
        WAX_REACTIVE_COOLDOWN_TICKS(0, 72000), WAX_MOLTEN_RADIUS(0, 64),
        WAX_MOLTEN_FIRE_TICKS(0, 72000), WAX_MOLTEN_TARGET_CAP(0, 64),
        WAX_REFUGE_INCOMING_MULTIPLIER(0, 10), WAX_SECOND_SKIN_ABSORPTION(0, 40),
        WAX_SECOND_SKIN_DURATION_TICKS(0, 72000), WAX_QUEEN_HEALTH_THRESHOLD(0, 1),
        WAX_QUEEN_RESISTANCE_AMPLIFIER(0, 10), WAX_QUEEN_RESISTANCE_TICKS(0, 72000),
        WAX_QUEEN_COOLDOWN_BONUS_TICKS(-72000, 72000), WAX_EMERGENCE_RADIUS(0, 64),
        WAX_EMERGENCE_DAMAGE_MULTIPLIER(0, 10), WAX_EMERGENCE_TARGET_CAP(0, 64),
        HIVE_PROC_DAMAGE_MULTIPLIER(0, 10), HIVE_PROC_COOLDOWN_BONUS_TICKS(-72000, 72000),
        HIVE_PROC_RANGE_BONUS(0, 128), HIVE_PROC_POISON_TICKS(0, 72000),
        HIVE_SHARED_TARGET_MULTIPLIER(0, 10), HIVE_SHARED_TARGET_TICKS(0, 72000),
        HIVE_TWIN_COUNT(0, 64), HIVE_TWIN_DAMAGE_MULTIPLIER(0, 10),
        HIVE_KILL_REFUND_TICKS(0, 72000), HIVE_EXECUTION_HEALTH_THRESHOLD(0, 1),
        HIVE_EXECUTION_DAMAGE_MULTIPLIER(0, 10), HIVE_EXECUTION_COOLDOWN_MULTIPLIER(0, 10),
        HIVE_BUSY_DAMAGE_MULTIPLIER(0, 10), HIVE_BUSY_BEE_CAP(0, 64),
        HIVE_SWARM_COUNT_BONUS(0, 64), HIVE_SWARM_COUNT_CAP(0, 64),
        HIVE_SWARM_RADIUS_BONUS(0, 64), HIVE_SWARM_SEARCH_CAP(0, 64),
        HIVE_SWARM_DURATION_BONUS_TICKS(0, 72000), HIVE_SWARM_STING_INTERVAL_TICKS(1, 72000),
        HIVE_SWARM_STING_COUNT(0, 64), HIVE_SWARM_SLOW_AMPLIFIER_BONUS(0, 10),
        HIVE_FOCUS_REQUIRED_STINGS(0, 64), HIVE_FOCUS_DAMAGE_MULTIPLIER(0, 10),
        HIVE_FOCUS_DURATION_TICKS(0, 72000), HIVE_CLOUD_COUNT(0, 64),
        HIVE_CLOUD_DAMAGE_MULTIPLIER(0, 10), HIVE_CLOUD_RADIUS(0, 64),
        HIVE_CLOUD_DURATION_MULTIPLIER(0, 10), HIVE_HUNT_COUNT(0, 64),
        HIVE_HUNT_DAMAGE_MULTIPLIER(0, 10), HIVE_HUNT_RADIUS(0, 64),
        HIVE_HUNT_STING_COUNT(0, 64), HIVE_HUNT_DURATION_TICKS(0, 72000),
        HIVE_WARD_ABSORPTION(0, 40), HIVE_WARD_DURATION_TICKS(0, 72000),
        HIVE_GUARD_RANGE(0, 64), HIVE_GUARD_INCOMING_MULTIPLIER(0, 10),
        HIVE_GUARD_LOCKOUT_TICKS(0, 72000), HIVE_WARNING_RADIUS(0, 64),
        HIVE_WARNING_DURATION_TICKS(0, 72000), HIVE_WARNING_LOCKOUT_TICKS(0, 72000),
        HIVE_RETORT_DAMAGE_MULTIPLIER(0, 10), HIVE_RETORT_LOCKOUT_TICKS(0, 72000),
        HIVE_RALLY_STING_COUNT(0, 64), HIVE_RALLY_RESISTANCE_TICKS(0, 72000),
        HIVE_ESCORT_BEE_COUNT(0, 64), HIVE_ESCORT_SPEED_MULTIPLIER(0, 10),
        HIVE_SAVE_HEALTH_THRESHOLD(0, 1), HIVE_SAVE_ABSORPTION_PER_BEE(0, 40),
        HIVE_SAVE_ABSORPTION_CAP(0, 40), HIVE_PHALANX_RANGE(0, 64),
        HIVE_PHALANX_BEE_COUNT(0, 64), HIVE_PHALANX_RESISTANCE_AMPLIFIER(0, 10),
        HIVE_VENGEFUL_DAMAGE_MULTIPLIER(0, 10), HIVE_VENGEFUL_RANGE(0, 64),
        CHOMP_PROC_DAMAGE_MULTIPLIER(0, 10), CHOMP_PROC_COOLDOWN_BONUS_TICKS(-72000, 72000),
        CHOMP_LIFESPAN_BONUS_TICKS(0, 72000), CHOMP_LOW_HEALTH_THRESHOLD(0, 1),
        CHOMP_LOW_HEALTH_DAMAGE_MULTIPLIER(0, 10), CHOMP_SPLASH_DAMAGE_MULTIPLIER(0, 10),
        CHOMP_SPLASH_RADIUS(0, 64), CHOMP_SPLASH_TARGET_CAP(0, 64),
        CHOMP_PACK_RANGE(0, 64), CHOMP_PACK_DAMAGE_PER_ALLY(0, 10), CHOMP_PACK_ALLY_CAP(0, 64),
        CHOMP_CHAIN_RANGE(0, 128), CHOMP_CHAIN_EXTENSION_TICKS(0, 72000),
        CHOMP_COLOSSAL_DAMAGE_MULTIPLIER(0, 10), CHOMP_COLOSSAL_SPLASH_MULTIPLIER(0, 10),
        CHOMP_COLOSSAL_SPLASH_RADIUS(0, 64), CHOMP_COLOSSAL_COOLDOWN_MULTIPLIER(0, 10),
        CHOMP_RELEASE_COUNT(0, 64),
        CHOMP_RELEASE_DAMAGE_MULTIPLIER(0, 10), CHOMP_RELEASE_LIFESPAN_TICKS(0, 72000),
        CHOMP_TARGET_RANGE_BONUS(0, 128), CHOMP_TARGET_SEARCH_CAP(0, 64),
        CHOMP_RALLY_SPEED_DURATION_TICKS(0, 72000), CHOMP_RALLY_SPEED_AMPLIFIER(0, 10),
        CHOMP_SHOULDER_AURA_BONUS(0, 64), CHOMP_HELPFUL_ABSORPTION(0, 40),
        CHOMP_HELPFUL_DURATION_TICKS(0, 72000), CHOMP_HELPFUL_LOCKOUT_TICKS(0, 72000),
        CHOMP_COORDINATED_DAMAGE_MULTIPLIER(0, 10), CHOMP_POUNCE_RANGE(0, 64),
        CHOMP_POUNCE_INTERVAL_TICKS(1, 72000), CHOMP_VICTORY_KILL_COUNT(0, 64),
        CHOMP_VICTORY_WINDOW_TICKS(0, 72000), CHOMP_VICTORY_REFUND_TICKS(0, 72000),
        CHOMP_BRIGADE_COUNT(0, 64), CHOMP_BRIGADE_AURA_MULTIPLIER(0, 10),
        CHOMP_HUNTER_COUNT(0, 64), CHOMP_HUNTER_DAMAGE_MULTIPLIER(0, 10),
        CHOMP_HUNTER_LIFESPAN_TICKS(0, 72000), CHOMP_BLUE_LIFESPAN_BONUS_TICKS(0, 72000),
        CHOMP_GRACE_DURATION_BONUS_TICKS(0, 72000), CHOMP_BLUE_DAMAGE_MULTIPLIER(0, 10),
        CHOMP_GUARD_RANGE(0, 64), CHOMP_GUARD_INCOMING_MULTIPLIER(0, 10),
        CHOMP_CLEANSE_LOCKOUT_TICKS(0, 72000), CHOMP_CLEANSE_EFFECT_COUNT(0, 64),
        CHOMP_RESCUE_HEALTH_THRESHOLD(0, 1), CHOMP_RESCUE_DURATION_TICKS(0, 72000),
        CHOMP_RESCUE_RESISTANCE_AMPLIFIER(0, 10), CHOMP_FIRST_BITE_REFUND_PERCENT(0, 100),
        CHOMP_ETERNAL_LIFESPAN_TICKS(0, 72000), CHOMP_ETERNAL_AURA_RADIUS(0, 64),
        CHOMP_RAVAGER_DAMAGE_MULTIPLIER(0, 10);

        private final double minimum;
        private final double maximum;

        Setting(double minimum, double maximum) {
            this.minimum = minimum;
            this.maximum = maximum;
        }

        double validate(double value) {
            return Math.clamp(Double.isFinite(value) ? value : minimum, minimum, maximum);
        }
    }

    public static final Phase7AbilityTuning EMPTY = new Phase7AbilityTuning(Map.of());
    private final EnumMap<Setting, Double> values;

    private Phase7AbilityTuning(Map<Setting, Double> values) {
        this.values = new EnumMap<>(Setting.class);
        this.values.putAll(values);
    }

    public double get(Setting setting, double fallback) {
        return values.getOrDefault(setting, setting.validate(fallback));
    }

    public int integer(Setting setting, int fallback) {
        return (int) Math.round(get(setting, fallback));
    }

    public boolean has(Setting setting) {
        return values.containsKey(setting);
    }

    public boolean flag(int bit) {
        return (integer(Setting.MODE, 0) & bit) != 0;
    }

    public Phase7AbilityTuning with(Setting setting, double value) {
        EnumMap<Setting, Double> updated = new EnumMap<>(values);
        updated.put(setting, setting.validate(value));
        return new Phase7AbilityTuning(updated);
    }

    public Phase7AbilityTuning add(Setting setting, double amount, double fallback) {
        return with(setting, get(setting, fallback) + amount);
    }

    public Phase7AbilityTuning multiply(Setting setting, double factor, double fallback) {
        return with(setting, get(setting, fallback) * factor);
    }
}
