package net.sweenus.simplyswords.api.ability;

import java.util.Collections;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.Map;

public final class StormSoulMasteryTuning implements MasteryTuningSnapshot {
    public enum Setting {
        COOLDOWN_TICKS(0, 72000), DURATION_TICKS(0, 72000), CHANCE(0, 100), RANGE(0, 128),
        RADIUS(0, 64), WIDTH(0, 64), HEIGHT(0, 64), DAMAGE_MULTIPLIER(0, 10), SPEED(0, 16),
        DELAY_TICKS(0, 72000), TRAVEL_TICKS(1, 1200), TETHER_RANGE(0, 128),
        GROWTH_PER_HIT(0, 1), GROWTH_CAP(0, 4), PULL_STRENGTH(-16, 16), TARGET_CAP(0, 64),
        STATUS_DURATION_TICKS(0, 72000), STATUS_AMPLIFIER(0, 10), HEAL_RATIO(0, 10), HEAL_CAP(0, 64),
        STACK_CAP(0, 64), STACK_DURATION_TICKS(0, 72000), PER_STACK_BONUS(0, 10), BONUS_CAP(0, 10),
        CHANCE_PER_FAILURE(0, 100), CHANCE_BONUS_CAP(0, 100),
        THRESHOLD(0, 128), LOCKOUT_TICKS(0, 72000), REFUND_TICKS(0, 72000),
        INTERVAL_TICKS(1, 72000), COUNT(0, 64), MOVEMENT_SPEED(0, 16), CLIMB_SPEED(0, 16),
        FINAL_WIDTH(0, 64), IMPACT_RADIUS(0, 64), IMPACT_DAMAGE_MULTIPLIER(0, 10),
        IMPACT_KNOCKBACK(0, 16), IMPACT_LIFT(0, 16), STAIN_RADIUS(0, 64),
        STAIN_DURATION_TICKS(0, 72000), COOLDOWN_MULTIPLIER(0, 10), DAMAGE_REDUCTION(0, 1),
        ABSORPTION(0, 40), ROD_DURATION_TICKS(0, 72000), SHIELD_DURATION_TICKS(0, 72000),
        CORRIDOR_MATERIALIZE_TICKS(0, 1200), CORRIDOR_HOLD_TICKS(0, 1200),
        CORRIDOR_CLOSE_TICKS(0, 1200), BEAM_DURATION_TICKS(0, 72000),
        MARK_DURATION_TICKS(0, 72000), BUFF_DURATION_TICKS(0, 72000),
        STRIDE_DURATION_TICKS(0, 72000), FLICKER_DURATION_TICKS(0, 1200),
        ABSORPTION_DURATION_TICKS(0, 72000), WOUND_DURATION_TICKS(0, 72000),
        WOUND_DAMAGE_MULTIPLIER(0, 10), MELEE_BONUS_PER_STACK(0, 10), MELEE_BONUS_CAP(0, 10),
        SLOW_DURATION_TICKS(0, 72000), WEAKNESS_DURATION_TICKS(0, 72000),
        REPOSITION_RANGE(0, 128), CHAIN_RANGE(0, 64), CENTER_RADIUS(0, 64), ROOT_RADIUS(0, 64),
        REVERSE_STRENGTH(0, 16), EDGE_BONUS(0, 4), CHAIN_TARGET_CAP(0, 64), ROOT_TARGET_CAP(0, 64),
        COOLDOWN_BASE_TICKS(0, 72000), RADIUS_CAP(0, 64), GROWTH_CAP_LIMIT(0, 10),
        CONDUCTIVE_TARGET_CAP(0, 64), CONDUCTIVE_DURATION_TICKS(0, 72000),
        PLANT_DAMAGE_MULTIPLIER(0, 10), SECOND_CHARGE_MULTIPLIER(0, 10),
        EXTRA_PULSE_MULTIPLIER(0, 10), INSTANT_PULSE_MULTIPLIER(0, 10),
        STORED_PULSE_MULTIPLIER(0, 10), STORED_PULSE_RADIUS(0, 64),
        CHAIN_DAMAGE_MULTIPLIER(0, 10), CENTER_DAMAGE_BONUS(0, 10),
        REPOSITION_DURATION_COST_TICKS(0, 72000), DOUBLE_CHARGE_LOCKOUT_TICKS(0, 72000),
        REVERSE_LOCKOUT_TICKS(0, 72000), WARD_LOCKOUT_TICKS(0, 72000),
        REVERSE_WEAKNESS_TICKS(0, 72000), ROOT_DURATION_TICKS(0, 72000),
        SURGE_INTERVAL(0, 64), WARD_TARGET_THRESHOLD(0, 64),
        RESERVE_INTERVAL_TICKS(0, 72000), RESERVE_REFUND_TICKS(0, 72000),
        SHIELD_THRESHOLD(0, 1), SHIELD_PUSH_STRENGTH(0, 16), SHIELD_LOCKOUT_TICKS(0, 72000),
        SHIELD_CUBE_COST(0, 8), SHIELD_LOW_HEALTH_THRESHOLD(0, 1),
        RESERVE_STACK_CAP(0, 32), RESERVE_STACK_DURATION_TICKS(0, 72000),
        RESERVE_STACK_BONUS(0, 10),
        ABILITY_DAMAGE_PENALTY(0, 1), ABILITY_DAMAGE_PER_CUBE(0, 10), ABILITY_DAMAGE_CUBE_CAP(0, 10),
        FOCUS_LANE_WIDTH(0, 64), FOCUS_DAMAGE_BONUS(0, 10),
        TRAP_MOVEMENT_SPEED(0, 1), BURST_STRENGTH(0, 16), BEAM_WIDTH_MULTIPLIER(0, 10),
        ARMOR_IGNORE(0, 30), CORRIDOR_TARGET_CAP(0, 64), BEAM_TARGET_CAP(0, 64),
        CHANCE_BONUS(0, 100), REPEAT_CHANCE_PENALTY(0, 100),
        FRESH_INK_STACKS(0, 16), FRESH_INK_LOCKOUT_TICKS(0, 72000),
        ECHO_CHANCE(0, 100), ECHO_RANGE(0, 64), ECHO_TARGET_CAP(0, 64),
        ECHO_DURATION_TICKS(0, 72000), ECHO_LOCKOUT_TICKS(0, 72000),
        REAP_STACK_BONUS(0, 10), REAP_STACK_BONUS_CAP(0, 10), REAP_TARGET_CAP(0, 64),
        HEAL_RATIO_BONUS(0, 10), HEAL_MULTIPLIER(0, 10),
        REAP_SPEED_THRESHOLD(0, 64), REAP_SPEED_DURATION_TICKS(0, 72000),
        REAP_HASTE_THRESHOLD(0, 64), REAP_HASTE_DURATION_TICKS(0, 72000),
        REAP_HASTE_AMPLIFIER(0, 10),
        REACH_BONUS_RANGE(0, 64), REACH_PULL_STRENGTH(0, 16), REACH_TARGET_CAP(0, 64),
        SHARED_END_DAMAGE_MULTIPLIER(0, 10), SHARED_END_RANGE(0, 64), SHARED_END_TARGET_CAP(0, 64),
        SHEATH_ABSORPTION(0, 40), SHEATH_DURATION_TICKS(0, 72000),
        PATIENCE_RANGE(0, 64), KNOCKBACK_RESISTANCE_BONUS(0, 1),
        BORROWED_TIME_TICKS(0, 72000), BORROWED_TIME_LOCKOUT_TICKS(0, 72000),
        COLD_GRIP_SLOW_TICKS(0, 72000), COLD_GRIP_LOCKOUT_TICKS(0, 72000), COLD_GRIP_TARGET_CAP(0, 64),
        GRAVE_RESERVE_RATIO(0, 10), GRAVE_RESERVE_CAP(0, 40),
        GRAVE_RESERVE_HEALTH_THRESHOLD(0, 1), GRAVE_RESERVE_DURATION_TICKS(0, 72000),
        QUIETUS_HEALTH_THRESHOLD(0, 1), QUIETUS_ABSORPTION(0, 40), QUIETUS_ABSORPTION_CAP(0, 40),
        UNBROKEN_MARK_THRESHOLD(0, 64), UNBROKEN_RANGE(0, 64), UNBROKEN_TARGET_CAP(0, 64),
        UNBROKEN_RESIST_TICKS(0, 72000), UNBROKEN_LOCKOUT_TICKS(0, 72000),
        SHELTER_ABSORPTION_RATIO(0, 10), SHELTER_ABSORPTION_CAP(0, 40), SHELTER_DURATION_TICKS(0, 72000),
        TITHE_KILL_BONUS(0, 10), TITHE_BONUS_CAP(0, 10), TITHE_DURATION_TICKS(0, 72000),
        TENDRIL_RANGE(0, 64), TENDRIL_LOCKOUT_TICKS(0, 72000), TENDRIL_SLOW_TICKS(0, 72000),
        TENDRIL_COUNT(0, 16), TENDRIL_REFUND_TICKS(0, 72000),
        GLOAM_DAMAGE_BONUS(0, 10), SEEKING_ROOT_RANGE(0, 64),
        SNARE_SLOW_TICKS(0, 72000), SNARE_SLOW_AMPLIFIER(0, 10), SNARE_LOCKOUT_TICKS(0, 72000),
        CLEAVE_RANGE(0, 64), CLEAVE_FINAL_WIDTH(0, 64), CLEAVE_INITIAL_WIDTH(0, 64),
        CLEAVE_DAMAGE_MULTIPLIER(0, 10), CLEAVE_COOLDOWN_MULTIPLIER(0, 10),
        CLEAVE_TARGET_CAP(0, 64), CLEAVE_SWING_COOLDOWN_TICKS(0, 1200),
        CLEAVE_HIT_BONUS(0, 10), CLEAVE_HIT_STACK_CAP(0, 64), CLEAVE_HIT_BONUS_CAP(0, 10),
        METEOR_CLEAVE_PENALTY(0, 10),
        FOOTFALL_RADIUS(0, 16), FOOTFALL_DAMAGE_MULTIPLIER(0, 10),
        TRAIL_STAIN_WIDTH(0, 16), TRAIL_STAIN_DURATION_TICKS(0, 72000),
        TRAIL_SLOW_AMPLIFIER(0, 4), TRAIL_SLOW_DURATION_TICKS(0, 72000),
        LEAP_IMPACT_DAMAGE_MULTIPLIER(0, 10), LEAP_IMPACT_RADIUS(0, 16),
        LEAP_IMPACT_KNOCKBACK(0, 16), LEAP_IMPACT_LIFT(0, 16), LEAP_IMPACT_TARGET_CAP(0, 64),
        LEAP_STAIN_RADIUS(0, 16), LEAP_STAIN_DURATION_TICKS(0, 72000), LEAP_CHARGE_THRESHOLD(0, 1),
        LEAP_CHARGED_DAMAGE_MULTIPLIER(0, 10), LEAP_CHARGED_RADIUS(0, 16),
        MOMENTUM_DISTANCE(0, 128), MOMENTUM_BONUS(0, 10),
        RIFT_RANGE(0, 64), RIFT_LOCKOUT_TICKS(0, 72000), RIFT_STAIN_RADIUS(0, 16),
        DASH_SPEED(0, 16), DASH_RADIUS(0, 64), DASH_TICKS(0, 1200),
        DASH_EXTENSION_PER_TARGET(0, 16), DASH_EXTENSION_CAP(0, 64), DASH_RANGE_MULTIPLIER(0, 10),
        DASH_ABSORPTION(0, 40), DASH_ABSORPTION_TICKS(0, 72000),
        WAKE_DURATION_TICKS(0, 72000), WAKE_SPEED_AMPLIFIER(0, 10), WAKE_KNOCKBACK_RESISTANCE(0, 1),
        PASSING_CUT_MULTIPLIER(0, 10), PASSING_CUT_TARGET_CAP(0, 64),
        RETURN_THRESHOLD(0, 64), RETURN_REFUND_TICKS(0, 72000),
        STRIKE_TARGET_CAP(0, 64), STRIKE_DAMAGE_MULTIPLIER(0, 10), STRIKE_COUNT(0, 16),
        STRIKE_INTERVAL_TICKS(0, 1200), STRIKE_NEAREST_ONLY(0, 1),
        BOUQUET_PER_TARGET_BONUS(0, 10), BOUQUET_TARGET_CAP(0, 64),
        FLOWERING_MULTIPLIER(0, 10), FLOWERING_RADIUS(0, 64), FLOWERING_TARGET_CAP(0, 64),
        ARMOR_IGNORE_RATIO(0, 1), ARMOR_IGNORE_CAP(0, 30),
        SOLO_DAMAGE_BONUS(0, 10), CROWD_THRESHOLD(0, 64), CROWD_DAMAGE_BONUS(0, 10),
        RHYTHM_CHANCE_PER_FAILURE(0, 100), RHYTHM_CHANCE_CAP(0, 100), RHYTHM_WINDOW_TICKS(0, 72000),
        READY_SPEED_AMPLIFIER(0, 10), FALL_DAMAGE_REDUCTION(0, 1),
        WINDBREAK_TICKS(0, 72000), WINDBREAK_PROJECTILE_REDUCTION(0, 1),
        REPRISE_WINDOW_TICKS(0, 72000), TEMPO_WINDOW_TICKS(0, 72000), TEMPO_DAMAGE_BONUS(0, 10),
        TEMPO_HASTE_TICKS(0, 72000),
        REFRESH_REFUND_TICKS(0, 72000), REFRESH_INTERVAL_TICKS(0, 72000), REFRESH_SPEED_TICKS(0, 72000),
        REFRESH_SPEED_AMPLIFIER(0, 10),
        STILL_WIND_THRESHOLD(0, 64), STILL_WIND_WINDOW_TICKS(0, 72000),
        STILL_WIND_MULTIPLIER(0, 10),
        REND_RANGE(0, 128), REND_WIDTH(0, 64), REND_SPEED(0, 16),
        REND_DAMAGE_MULTIPLIER(0, 10), REND_TARGET_CAP(0, 64), REND_STOP_ON_HIT(0, 1),
        LEECH_RATIO(0, 1), LEECH_CAP(0, 64),
        COLLISION_MULTIPLIER(0, 10), COLLISION_RADIUS(0, 64), COLLISION_TARGET_CAP(0, 64),
        MOMENTUM_SPEED_BONUS(0, 10), MOMENTUM_SPEED_CAP(0, 10),
        MOMENTUM_DAMAGE_BONUS(0, 10), MOMENTUM_DAMAGE_CAP(0, 10),
        WOUND_WEAKNESS_TICKS(0, 72000), WOUND_AGE_BONUS(0, 10), WOUND_AGE_CAP(0, 10),
        WOUND_AGE_INTERVAL_TICKS(1, 72000),
        SPLINTER_MULTIPLIER(0, 10), SPLINTER_RANGE(0, 64),
        REOPEN_CHANCE(0, 100), REOPEN_DURATION_TICKS(0, 72000), REOPEN_LOCKOUT_TICKS(0, 72000),
        MORTAL_THRESHOLD(0, 1), MORTAL_BONUS(0, 10), MORTAL_BOSS_BONUS(0, 10),
        SPREAD_COUNT(0, 16), SPREAD_RANGE(0, 64), SPREAD_DURATION_TICKS(0, 72000),
        TRAIL_SLOW_LEVEL(0, 4), TRAIL_SLOW_TICKS(0, 72000),
        VEIL_DURATION_TICKS(0, 1200), GLOAM_DAMAGE_RIDER(0, 10),
        RECALL_RANGE(0, 64), RECALL_STRENGTH(0, 16), RECALL_TARGET_CAP(0, 64),
        SHELTER_ABSORPTION_PER_HIT(0, 40), SHELTER_ABSORPTION_LIMIT(0, 40), SHELTER_BUFF_TICKS(0, 72000),
        FOOTPRINT_TICKS(0, 72000), FOOTPRINT_PROJECTILE_REDUCTION(0, 1),
        LIVING_SHADOW_TICKS(0, 72000), LIVING_SHADOW_INTERVAL(1, 1200),
        LIVING_SHADOW_MULTIPLIER(0, 10), LIVING_SHADOW_TARGET_CAP(0, 64),
        VOID_COLLAPSE_MULTIPLIER(0, 10), VOID_COLLAPSE_RADIUS(0, 64), VOID_COLLAPSE_TARGET_CAP(0, 64),
        MODE(0, 1048575);

        private final double minimum;
        private final double maximum;

        Setting(double minimum, double maximum) {
            this.minimum = minimum;
            this.maximum = maximum;
        }

        double validate(double value) {
            return Math.clamp(Double.isFinite(value) ? value : minimum, minimum, maximum);
        }
    }

    public static final StormSoulMasteryTuning EMPTY = new StormSoulMasteryTuning(Map.of());
    private final EnumMap<Setting, Double> values;

    private StormSoulMasteryTuning(Map<Setting, Double> values) {
        this.values = new EnumMap<>(Setting.class);
        this.values.putAll(values);
    }

    public double get(Setting setting, double fallback) {
        return values.getOrDefault(setting, setting.validate(fallback));
    }

    public int integer(Setting setting, int fallback) {
        return (int) Math.round(get(setting, fallback));
    }

    public boolean flag(Setting setting) {
        return get(setting, 0) >= 1;
    }

    public boolean has(Setting setting) {
        return values.containsKey(setting);
    }

    public StormSoulMasteryTuning with(Setting setting, double value) {
        EnumMap<Setting, Double> updated = new EnumMap<>(values);
        updated.put(setting, setting.validate(value));
        return new StormSoulMasteryTuning(updated);
    }

    public StormSoulMasteryTuning add(Setting setting, double amount, double fallback) {
        return with(setting, get(setting, fallback) + amount);
    }

    public StormSoulMasteryTuning multiply(Setting setting, double factor, double fallback) {
        return with(setting, get(setting, fallback) * factor);
    }

    @Override
    public Map<String, Double> entries() {
        Map<String, Double> entries = new LinkedHashMap<>();
        values.forEach((setting, value) -> entries.put(setting.name(), value));
        return Collections.unmodifiableMap(entries);
    }
}
